image:
  name: 'python:3.8'
deploy:
  - step: &deploy
      script:
        - |
          if [ $BITBUCKET_BRANCH == 'develop' ]; then
            export S3_BUCKET='dev-3beep-file-storage-service'
            export STACK_NAME='Dev3beepFileStorageService'
            export STAGE_NAME='dev'
            export ENVIRONMENT_NAME='Dev'
          fi
        - |
          if [ $BITBUCKET_BRANCH == 'master' ]; then
            export S3_BUCKET='prod-3beep-file-storage-service'
            export STACK_NAME='Prod3beepFileStorageService'
            export STAGE_NAME='prod'
            export ENVIRONMENT_NAME='Prod'
          fi
        - pipe: atlassian/aws-s3-deploy:0.4.5
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            S3_BUCKET: $S3_BUCKET
            LOCAL_PATH: '$(pwd)'
            EXTRA_ARGS: '--exclude=* --include=template.yaml'
            DELETE_FLAG: 'true'
            DEBUG: 'true'
        - export CLOUDFORMATION_TEMPLATE="https://$S3_BUCKET.s3.$AWS_DEFAULT_REGION.amazonaws.com/template.yaml"
        - pipe: 'atlassian/aws-sam-deploy:0.5.2'
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            S3_BUCKET: $S3_BUCKET
            STACK_NAME: $STACK_NAME
            CAPABILITIES:
              - CAPABILITY_IAM
              - CAPABILITY_NAMED_IAM
              - CAPABILITY_AUTO_EXPAND
            TEMPLATE: $CLOUDFORMATION_TEMPLATE
            STACK_PARAMETERS: |
              [
                {
                  'ParameterKey': 'StageName',
                  'ParameterValue': '${STAGE_NAME}'
                },
                {
                  'ParameterKey': 'EnvironmentName',
                  'ParameterValue': '${ENVIRONMENT_NAME}'
                },
                {
                  'ParameterKey': 'S3AccessKeyId',
                  'ParameterValue': '${AWS_ACCESS_KEY_ID}'
                },
                {
                  'ParameterKey': 'S3SecretAccessKey',
                  'ParameterValue': '${AWS_SECRET_ACCESS_KEY}'
                },
                {
                  'ParameterKey': 'S3Bucket',
                  'ParameterValue': '${S3_BUCKET}'
                }
              ]
            WAIT: 'true'
            WAIT_INTERVAL: 60
            DEBUG: 'true'
pipelines:
  branches:
    develop:
      - step: *deploy
    master:
      - step: *deploy
